### PR TITLE
Assign materials in document order for MaterialXView

### LINKED ISSUE #1108: <materialassign> elements not processed in-order in MaterialXView
The spec says on p. 71 in "MaterialAssign Elements" that "assign declarations should be processed in the order they appear in the file, and if any geometry appears in multiple \<materialassign\>s, the last \<materialassign\> wins".

However, this behaviour can not be observed in MaterialXView.

To reproduce, load the _shaderball.glb_ geometry and following document:
```xml
<?xml version="1.0"?>
<materialx version="1.38">

  <standard_surface name="SR_red" type="surfaceshader">
    <input name="base_color" type="color3" value="1, 0, 0" />
  </standard_surface>
  <surfacematerial name="Red" type="material">
    <input name="surfaceshader" type="surfaceshader" nodename="SR_red" />
  </surfacematerial>

  <standard_surface name="SR_blue" type="surfaceshader">
    <input name="base_color" type="color3" value="0, 0, 1" />
  </standard_surface>
  <surfacematerial name="Blue" type="material">
    <input name="surfaceshader" type="surfaceshader" nodename="SR_blue" />
  </surfacematerial>

  <look name="Look">
    <materialassign name="Blue_P" geom="/Preview_Mesh" material="Blue" />
    <materialassign name="Red_P" geom="/Preview_Mesh" material="Red" />
    <materialassign name="Blue_C" geom="/Calibration_Mesh" material="Blue" />
    <materialassign name="Red_C" geom="/Calibration_Mesh" material="Red" />
  </look>

</materialx>
```

2022-10-18 22_21_21-Window
The Blue material is assigned, but it should be Red.

### PR DESCRIPTION
**Pull request by kwokcb**
Fixes #1108 (desktop)

## Fix
* The previous ordering for MaterialXView (desktop) was by materials found which does not necessarily match the order for assignments in any existing look. Change to go once through any looks.
* No changes are required for web as this already traverses by look.

## Results
* Test:
```XML
<?xml version="1.0"?>
<materialx version="1.38">
  <!-- Simple test to check look assignment order. The target geometry
       is assumed to be the default shader ball with the intended
       result being that the Preview mesh is "blue" and the Calibration mesh is
       "red.
  -->    
  <standard_surface name="Red_Shader" type="surfaceshader">
    <input name="base_color" type="color3" value="1, 0, 0" />
  </standard_surface>
  <surfacematerial name="Red_Material" type="material">
    <input name="surfaceshader" type="surfaceshader" nodename="Red_Shader" />
  </surfacematerial>

  <standard_surface name="Blue_Shader" type="surfaceshader">
    <input name="base_color" type="color3" value="0, 0, 1" />
  </standard_surface>
  <surfacematerial name="Blue_Material" type="material">
    <input name="surfaceshader" type="surfaceshader" nodename="Blue_Shader" />
  </surfacematerial>

  <look name="Look">
    <materialassign name="Red_Preview" geom="/Preview_Mesh" material="Red_Material" />
    <materialassign name="Blue_Preview" geom="/Preview_Mesh" material="Blue_Material" />
    <materialassign name="Blue_Calibration" geom="/Calibration_Mesh" material="Blue_Material" />
    <materialassign name="Red_Calibration" geom="/Calibration_Mesh" material="Red_Material" />
  </look>
</materialx>

```
* Web results on left with sample file, and desktop on right for comparison
image

### CODE REVIEW

File: source/MaterialXView/Viewer.cpp [hunk 1]
```diff
@@ -1308,25 +1308,56 @@ void Viewer::loadDocument(const mx::FilePath& filename, mx::DocumentPtr librarie
...
                     mat->generateShader(_genContext);
                 }
-
-                mx::NodePtr materialNode = mat->getMaterialNode();
-                if (materialNode)
+            }
+       
+            // For document assignment we must go in order of assignments for looks
+            // with later assignments superceding earlier ones.
+            for (mx::LookPtr look : doc->getLooks())
```
Comment (kwokcb) [inline source/MaterialXView/Viewer.cpp:1315]: Previous logic was to traverse through materials found in the document and then find the match in the look assignments in order. This can give incorrect results. Instead traverse by look first and match with materials found. This allows for the "last match" to set the final material assignment.

**Review by jstone-lucasfilm — APPROVED** [review]
Looks good to me, thanks @kwokcb!
