### PR TITLE
Fixed null check in Graph::propertyEditor

### LINKED ISSUE #1600: Crash in `Graph::propertyEditor` due to absence of null check
I reproduced with the following steps:

1. Open some simple mtlx containing a nodegraph.
2. Click on the nodegraph to select it then doubleclick to open it.
3. Click on a surfaceshader node.
4. Click on the name property editor and press `Backspace` to drop some chars. Immediate seg fault!

Using gdb, I find out the null pointer problem causing crash in some shared_ptr code. I have the incoming PR.

Found while experimenting with #1596.

### PR DESCRIPTION
**Pull request by eytienne**
Fixes #1600

### CODE REVIEW

File: source/MaterialXGraphEditor/Graph.cpp [hunk 1]
```diff
@@ -3349,7 +3349,7 @@ void Graph::propertyEditor()
                         }
                         else
                         {
-                            nodes->getOutput()->setConnectedNode(_currUiNode->getNode());
+                            uiNode->getOutput()->setConnectedNode(_currUiNode->getNode());
```
Comment (eytienne) [inline source/MaterialXGraphEditor/Graph.cpp:3352]: Code smell: looking at the enclosing if sequence, `_currUiNode->getNode()` will always be null.

**Comment by jstone-lucasfilm** [comment]
This looks very promising, thanks @eytienne!  I'm CC'ing @lfl-eholthouser for her thoughts on the proposed fix.

**Review by lfl-eholthouser — APPROVED** [review]

**Review by jstone-lucasfilm — APPROVED** [review]
Thanks for the fix, @eytienne!
