### PR TITLE
Fix handling of unrecognized types in Web Viewer

### LINKED ISSUE #1704: Web Viewer : Crash when loading shaders with unsupported input types
## Issue

The web viewer will "crash" due to infinite recursive calls when trying to parse shader inputs.
"Unknown" types call back into parsing continuously until the call stack is "blown".

### Example

Try loading in [lama_tests.mtlx](https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/resources/Materials/TestSuite/pbrlib/surfaceshader/lama_tests.mtlx) test file. This file has for instance `BSDF` type inputs exposed.

The resulting error when dropping it in to the viewer.
```
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at toThreeUniform (webpack://MaterialXView/./source/helper.js?:99:24)
    at toThreeUniform (webpack://MaterialXView/./source/helper.js?:142:24)
    at toThreeUniform (webpack://MaterialXView/./source/helper.js?:142:24)
    at toThreeUniform (webpack://MaterialXView/./source/helper.js?:142:24)
    at toThreeUniform (webpack://MaterialXView/./source/helper.js?:142:24)
    at toThreeUniform (webpack://MaterialXView/./source/helper.js?:142:24)
    at toThreeUniform (webpack://MaterialXView/./source/helper.js?:142:24)
    at toThreeUniform (webpack://MaterialXView/./source/helper.js?:142:24)
    at toThreeUniform (webpack://MaterialXView/./source/helper.js?:142:24)
    at toThreeUniform (webpack://MaterialXView/./source/helper.js?:142:24)
```

 ## Proposed Fix
- Remove recursive calls for unknown types as it is assumed they cannot be bound to since they are not supported.

### PR DESCRIPTION
**Pull request by kwokcb**
## Issue

Fixes #1704 

## Change

Remove recursive call which appears to be unfinished code, and even has the wrong number of args to the call.

## Test
- `lama_test.mtlx`

image

### CODE REVIEW

File: javascript/MaterialXView/source/helper.js [hunk 1]
```diff
@@ -127,10 +127,8 @@ function toThreeUniform(type, value, name, uniforms, textureLoader, searchPath,
             break;
         case 'samplerCube':
         case 'string':
-            break;
         default:
-            // struct
-            outValue = toThreeUniform(value);
```
Comment (kwokcb) [inline javascript/MaterialXView/source/helper.js:133]: Remove non-sensical recursive call.

**Review by jstone-lucasfilm — APPROVED** [review]
Good catch, thanks @kwokcb!
